### ISSUE TITLE
Auctionator - Skin

### ISSUE THREAD

**Issue by crumdidlyumshis** [ElvUI/ElvUI_AddOnSkins#1]
![wowscrnshot_111315_184722](https://cloud.githubusercontent.com/assets/7307335/11160930/15273086-8a37-11e5-8e3c-1db85261ab38.jpg)

**Comment by Bunny67** [comment]
Not yet added

**Comment by crumdidlyumshis** [comment]
Just a reminder! ^^

**Comment by crumdidlyumshis** [comment]
Thank you! Closing
