### ISSUE TITLE
FlightMap - Skin

### ISSUE THREAD

**Issue by crumdidlyumshis** [ElvUI/ElvUI_AddOnSkins#11]
Could you add this? http://git.tukui.org/Elv/elvui/blob/2c4910a27931833138b5f7d9cdc566fa8554cf06/ElvUI_AddOnSkins/skins/FlightMap.lua

http://git.tukui.org/Elv/elvui/blob/2c4910a27931833138b5f7d9cdc566fa8554cf06/ElvUI_AddOnSkins/core/core.lua#L154

**Comment by Bunny67** [comment]
added
