### ISSUE TITLE
AtlasLoot - Skin

### ISSUE THREAD

**Issue by Nzith** [ElvUI/ElvUI_AddOnSkins#12]
First of all i want to thank you for skinning this add-on, its amazing!
Now i have noticed that somethings are missing and it feels incomplete.
The menus and the tooltips are not skinned.  I don't know if you have the time to do it but if you can it would be nice!

![1](https://cloud.githubusercontent.com/assets/16617127/12212113/4251e74a-b66f-11e5-9a8b-0919df43c63a.jpg)
![2](https://cloud.githubusercontent.com/assets/16617127/12212114/42e74f92-b66f-11e5-9516-82cc94636d34.jpg)
![3](https://cloud.githubusercontent.com/assets/16617127/12212115/43b6b69c-b66f-11e5-9a92-00e312fe387a.jpg)
![5](https://cloud.githubusercontent.com/assets/16617127/12212116/4487fedc-b66f-11e5-9ab3-e815a698b899.jpg)

**Comment by Bunny67** [comment]
ItemTooltip skinned
DropDownMenu not skinned

**Comment by crumdidlyumshis** [comment]
bump

**Comment by Bunny67** [comment]
DropDownMenu skinned
