### ISSUE TITLE
Skin for WeakAuras

### ISSUE THREAD

**Issue by ukkoclap** [ElvUI/ElvUI_AddOnSkins#14]
Hi, when I played last time on retail MoP WeakAuras was skinned. I would like to make the suggestion for a skin for WeakAuras,

**Comment by xeek** [comment]
would love that too, Weakauras R14 is the version that works with 3.3.5 btw

**Comment by ukkoclap** [comment]
WA R14 is the old version actually. The MoP version of WA 2.0.8 has been backported for 3.3.5 and is fully functional.

**Comment by Bunny67** [comment]
please url

**Comment by xeek** [comment]
yes please link the backported one, I tried searching for it but couldn't find it, the Version doesn't really have that much options

**Comment by Bunny67** [comment]
added skin

**Comment by crumdidlyumshis** [comment]
Does this need to be closed?
