### ISSUE TITLE
DBM not skinned after last update

### ISSUE THREAD

**Issue by xeek** [ElvUI/ElvUI_AddOnSkins#15]
title should explain everything
![wowscrnshot_021516_205004](https://cloud.githubusercontent.com/assets/1155949/13060906/fd2d3c6c-d434-11e5-8cb7-919fc0c58f3b.jpg)

**Comment by Bunny67** [comment]
strange that does not work, since I work
![wowscrnshot_021616_173025](https://cloud.githubusercontent.com/assets/5816685/13079015/2d9b0d04-d4d3-11e5-8096-bb0371922112.jpg)

**Comment by xeek** [comment]
problem was on my side sorry

**Comment by Bunny67** [comment]
removed

**Comment by xeek** [comment]
fixed thanks
