### ISSUE TITLE
Overachiever - Skin

### ISSUE THREAD

**Issue by crumdidlyumshis** [ElvUI/ElvUI_AddOnSkins#16]
Would it be possible to add http://www.curse.com/addons/wow/overachiever?

![Alt text](http://media-curse.cursecdn.com/attachments/16/987/6539050fef5eaf76f2275445ec469f99.jpg)

**Comment by Bunny67** [comment]
check

**Comment by crumdidlyumshis** [comment]
Wow thank you! It works :dancer:
