### ISSUE TITLE
CallToArms - Skin

### ISSUE THREAD

**Issue by crumdidlyumshis** [ElvUI/ElvUI_AddOnSkins#2]
My first time creating a skin from scratch! :dancer: 

Could you add this? http://pastebin.com/JyhS3ndx

![wowscrnshot_111615_011507](https://cloud.githubusercontent.com/assets/7307335/11176350/b46bce74-8c01-11e5-9572-a1602f85fdfe.jpg)
![wowscrnshot_111615_011447](https://cloud.githubusercontent.com/assets/7307335/11176351/b46d52d0-8c01-11e5-9019-c50e558989c5.jpg)

http://www.wowinterface.com/downloads/info11830-CallToArmsmonitorLFGchannel.html#info

**Comment by crumdidlyumshis** [comment]
Added to latest. Closing. Thank you Bunny67!

**Comment by crumdidlyumshis** [comment]
Quick Question. How do I center the text vertically in the tabs?

![b46bce74-8c01-11e5-9572-a1602f85fdfe](https://cloud.githubusercontent.com/assets/7307335/11186926/b77837d6-8c49-11e5-9d12-2ebe4265dd45.jpg)

**Comment by Bunny67** [comment]
_G[tabName.."Text"]:SetPoint("CENTER", 0, 0);

orinal point "CENTER", 0, 9 as far as I understand this addon

**Comment by Bunny67** [comment]
https://github.com/ElvUI/ElvUI_AddOnSkins/commit/8262c7281aaf365e149baa3ece1b5b2292739c1f
