### ISSUE TITLE
Gearscore - Skin

### ISSUE THREAD

**Issue by Lexblack** [ElvUI/ElvUI_AddOnSkins#20]
Just skinned this addon. I couldn't skin the Report button and i couldn't figure out how to replace the blue background with the default elvui color, if you can finish it please do cause i can't. Here are some screenshots and the code.

http://i.imgur.com/cQPCh6U.jpg
http://i.imgur.com/84iUoPz.jpg
http://i.imgur.com/oZ5MQSQ.jpg
http://i.imgur.com/IQXCQcj.jpg

local E, L, V, P, G, _ = unpack(ElvUI);
local addon = E:GetModule("AddOnSkins");

if(not addon:CheckAddOn("GearScore")) then return; end

function addon:GearScore()
	local S = E:GetModule("Skins");
	GS_DefaultFrame:StripTextures();
	GS_DisplayFrame:StripTextures();
	GS_DisplayFrame:SetTemplate("Transparent");
	GS_ReportFrame:StripTextures();
	GS_ReportFrame:SetTemplate("Transparent");
	GS_DatabaseFrame:StripTextures();
	GS_DatabaseFrame:SetTemplate("Transparent");
	GS_Model:StripTextures();
	GS_Model:SetTemplate('Default');
	GS_GearCheckFrame:StripTextures();
	GS_GearCheckFrame:SetTemplate('Default');
	GS_NotesEditBox:StripTextures();
	GS_NotesEditBox:SetTemplate('Default');
	GS_NotesFrame:StripTextures();
	GS_NotesFrame:SetTemplate('Default');

	S:HandleCloseButton(GSDisplayFrameCloseButton);
	S:HandleCloseButton(GSReportFrameCloseButton);
	S:HandleCloseButton(GSDatabaseFrameCloseButton);
	S:HandleButton(GS_SearchButton);
	S:HandleButton(GS_DeleteButton);
	S:HandleButton(GS_InviteButton);
	S:HandleButton(GS_GroupButton);
	S:HandleButton(GS_UndoButton);
	S:HandleButton(Button3);
	S:HandleButton(GS_PreviousButton);
	S:HandleButton(GS_NextButton);
	S:HandleButton(GS_Search2Button);
	GS_Search2Button:SetWidth(65);
	S:HandleButton(GS_BackProfileButton);
	S:HandleButton(GSXButton1);
	S:HandleEditBox(GS_EditBox1);
	GS_EditBox1:SetHeight(27);
	S:HandleEditBox(GS_LevelEditBox);
	GS_LevelEditBox:SetHeight(22);
	GS_LevelEditBox:SetWidth(22);
	S:HandleEditBox(GS_SearchXBox);
	GS_SearchXBox:SetHeight(22);
	GS_SearchXBox:SetWidth(125);
	S:HandleEditBox(GSX_WhisperEditBox);
	GSX_WhisperEditBox:SetHeight(22);
	S:HandleEditBox(GSX_ChannelEditBox);
	GSX_ChannelEditBox:SetHeight(22);
	S:HandleSliderFrame(GS_Slider);
	S:HandleSliderFrame(GS_DatabaseAgeSlider);
	S:HandleCheckBox(GS_ShowPlayerCheck);
	S:HandleCheckBox(GS_Heavy);
	S:HandleCheckBox(GS_None);
	S:HandleCheckBox(GS_Light);
	S:HandleCheckBox(GS_ShowItemCheck);
	S:HandleCheckBox(GS_LevelCheck);
	S:HandleCheckBox(GS_SpecScoreCheck1);
	S:HandleCheckBox(GS_SpecScoreCheck2);
	S:HandleCheckBox(GS_SpecScoreCheck3);
	S:HandleCheckBox(GS_SpecScoreCheck4);
	S:HandleCheckBox(GS_DetailCheck);
	S:HandleCheckBox(GS_DateCheck);
	S:HandleCheckBox(GS_HelpCheck);
	S:HandleCheckBox(GS_ChatCheck);
	S:HandleCheckBox(GS_MasterlootCheck);
	S:HandleCheckBox(GS_PruneCheck);
	S:HandleCheckBox(GS_FactionCheck);
	S:HandleCheckBox(GSXSayCheck);
	S:HandleCheckBox(GSXPartyCheck);
	S:HandleCheckBox(GSXRaidCheck);
	S:HandleCheckBox(GSXGuildCheck);
	S:HandleCheckBox(GSXOfficerCheck);
	S:HandleCheckBox(GSXWhisperTargetCheck);
	S:HandleCheckBox(GSXWhisperCheck);
	S:HandleCheckBox(GSXChannelCheck);

	GS_SpecBar1:StripTextures();
	GS_SpecBar2:StripTextures();
	GS_SpecBar3:StripTextures();
	GS_SpecBar4:StripTextures();
	GS_SpecBar1:SetStatusBarTexture(E.media.normTex);
	GS_SpecBar2:SetStatusBarTexture(E.media.normTex);
	GS_SpecBar3:SetStatusBarTexture(E.media.normTex);
	GS_SpecBar4:SetStatusBarTexture(E.media.normTex);
	GS_SpecBar1:CreateBackdrop('Default');
	GS_SpecBar2:CreateBackdrop('Default');
	GS_SpecBar3:CreateBackdrop('Default');
	GS_SpecBar4:CreateBackdrop('Default');
	E:RegisterStatusBar(GS_GearFrame);

	GS_XpBar1:StripTextures();
	GS_XpBar2:StripTextures();
	GS_XpBar3:StripTextures();
	GS_XpBar4:StripTextures();
	GS_XpBar5:StripTextures();
	GS_XpBar6:StripTextures();
	GS_XpBar7:StripTextures();
	GS_XpBar8:StripTextures();
	GS_XpBar9:StripTextures();
	GS_XpBar10:StripTextures();
	GS_XpBar11:StripTextures();
	GS_XpBar12:StripTextures();
	GS_XpBar13:StripTextures();
	GS_XpBar14:StripTextures();
	GS_XpBar1:SetStatusBarTexture(E.media.normTex);
	GS_XpBar2:SetStatusBarTexture(E.media.normTex);
	GS_XpBar3:SetStatusBarTexture(E.media.normTex);
	GS_XpBar4:SetStatusBarTexture(E.media.normTex);
	GS_XpBar5:SetStatusBarTexture(E.media.normTex);
	GS_XpBar6:SetStatusBarTexture(E.media.normTex);
	GS_XpBar7:SetStatusBarTexture(E.media.normTex);
	GS_XpBar8:SetStatusBarTexture(E.media.normTex);
	GS_XpBar9:SetStatusBarTexture(E.media.normTex);
	GS_XpBar10:SetStatusBarTexture(E.media.normTex);
	GS_XpBar11:SetStatusBarTexture(E.media.normTex);
	GS_XpBar12:SetStatusBarTexture(E.media.normTex);
	GS_XpBar13:SetStatusBarTexture(E.media.normTex);
	GS_XpBar14:SetStatusBarTexture(E.media.normTex);
	GS_XpBar1:CreateBackdrop('Default');
	GS_XpBar2:CreateBackdrop('Default');
	GS_XpBar3:CreateBackdrop('Default');
	GS_XpBar4:CreateBackdrop('Default');
	GS_XpBar5:CreateBackdrop('Default');
	GS_XpBar6:CreateBackdrop('Default');
	GS_XpBar7:CreateBackdrop('Default');
	GS_XpBar8:CreateBackdrop('Default');
	GS_XpBar9:CreateBackdrop('Default');
	GS_XpBar10:CreateBackdrop('Default');
	GS_XpBar11:CreateBackdrop('Default');
	GS_XpBar12:CreateBackdrop('Default');
	GS_XpBar13:CreateBackdrop('Default');
	GS_XpBar14:CreateBackdrop('Default');
	E:RegisterStatusBar(GS_ExPFrame);

	for i = 1, 4 do
		S:HandleTab(_G["GS_DatabaseFrameTab" .. i]);
	end

	for i = 1, 3 do
		S:HandleTab(_G["GS_DisplayFrameTab" .. i]);
	end

end

addon:RegisterSkin("GearScore", addon.GearScore);

**Comment by Lexblack** [comment]
I found a way to skin the Report button but i had to edit something in the Addon code.
http://imgur.com/VTnEeoe

**Comment by Bunny67** [comment]
Not finished

**Comment by Bunny67** [comment]
I think finished
