### ISSUE TITLE
EveryQuest - Skin

### ISSUE THREAD

**Issue by Lexblack** [ElvUI/ElvUI_AddOnSkins#22]
I Skinned this addon.

Code:
local E, L, V, P, G, _ = unpack(ElvUI);
local addon = E:GetModule("AddOnSkins");

if(not addon:CheckAddOn("EveryQuest")) then return; end

function addon:EveryQuest()
	local S = E:GetModule("Skins");

	EveryQuestFrame:StripTextures();
	EveryQuestFrame:SetTemplate("Transparent");
	EveryQuestListScrollFrame:CreateBackdrop("Default");
	S:HandleDropDownBox(EQ_Menu)
	EQ_Menu:SetWidth(190);
	S:HandleButton(EveryQuestExitButton);
	S:HandleCloseButton(EveryQuestFrameCloseButton)
	S:HandleButton(EQ_Options)
	S:HandleButton(EQ_Filters)
	S:HandleButton(EQ_ToggleButton)
	EQ_ToggleButton:SetWidth(50);
	EQ_ToggleButton:SetHeight(25);
	S:HandleScrollBar(EveryQuestListScrollFrameScrollBar)

end

addon:RegisterSkin("EveryQuest", addon.EveryQuest);

Pictures:
![everyquest1](https://cloud.githubusercontent.com/assets/16202997/14578697/7d263d24-0397-11e6-92ae-73986163acbd.png)
![everyquest2](https://cloud.githubusercontent.com/assets/16202997/14578698/80c753dc-0397-11e6-8439-4c5c4c00df58.png)
![everyquest3](https://cloud.githubusercontent.com/assets/16202997/14578699/83729d8a-0397-11e6-80ce-93440375b489.png)

It will only work with this version:
http://www.mediafire.com/download/5ik5midmec2u72a/EveryQuest+3.3.5+[ElvUI].rar

**Comment by crumdidlyumshis** [comment]
Awesome thank you for this! I never could get EveryQuest to work right for 3.3.5. Where might I ask, did you a correct version from?

**Comment by Lexblack** [comment]
The version of the addon is the latest for the 3.3.5 client. But i had to edit some lines in the addon so it could be fully skinned. Unfortunatly without editing it it can't be fully skinned.
I did this for almost all the addons i use that can't be skinned without editing the original addon code.
I'm not sure if sharing the skin code with the edited addon will do more good than bad.

**Comment by Lexblack** [comment]
Some changes in Size and Button Position.
![everyquest1](https://cloud.githubusercontent.com/assets/16202997/14606930/118a5206-0588-11e6-9d5e-dbee937a8fd0.png)

Code:
local E, L, V, P, G, _ = unpack(ElvUI);
local addon = E:GetModule("AddOnSkins");

if(not addon:CheckAddOn("EveryQuest")) then return; end

function addon:EveryQuest()
	local S = E:GetModule("Skins");

	EveryQuestFrame:StripTextures();
	EveryQuestFrame:SetTemplate("Transparent");
	EveryQuestListScrollFrame:CreateBackdrop("Default");
	EveryQuestFrame:SetScale(0.9)
	S:HandleDropDownBox(EQ_Menu)
	EQ_Menu:SetWidth(220);
	EQ_Menu:SetScale(1.10)
	S:HandleButton(EveryQuestExitButton);
	S:HandleCloseButton(EveryQuestFrameCloseButton)
	S:HandleButton(EQ_Options)
	EQ_Options:SetScale(1.15)
	EQ_Options:SetWidth(80)
	S:HandleButton(EQ_Filters)
	EQ_Filters:SetScale(1.11)
	EQ_Filters:SetWidth(83)
	S:HandleButton(EQ_ToggleButton)
	EQ_ToggleButton:SetWidth(50);
	EQ_ToggleButton:SetHeight(25);
	S:HandleScrollBar(EveryQuestListScrollFrameScrollBar)

	EveryQuestFrame:SetWidth(350)
	EveryQuestExitButton:Point("BOTTOMRIGHT", EveryQuestFrame, "BOTTOMRIGHT", -130, 3)
	EveryQuestFrameCloseButton:Point("TOPRIGHT", EveryQuestFrame, "TOPRIGHT", 4, 5)
	EQ_Menu:Point("TOPRIGHT", EveryQuestFrame, "TOPRIGHT", -20, -35)
	EQ_Options:Point("TOPLEFT", EveryQuestFrame, "TOPLEFT", 5, -10)
	EQ_Filters:Point("BOTTOMLEFT", EveryQuestFrame, "BOTTOMLEFT", 5, 403)
	EQ_ToggleButton:Point("TOPLEFT",QuestLogFrame, "TOPLEFT", 20, -40)

end

addon:RegisterSkin("EveryQuest", addon.EveryQuest);

**Comment by Bunny67** [comment]
Check
