### ISSUE TITLE
Gnomish Vendor Shrinker - Skin

### ISSUE THREAD

**Issue by Lexblack** [ElvUI/ElvUI_AddOnSkins#24]
Code:
local E, L, V, P, G, _ = unpack(ElvUI);
local addon = E:GetModule("AddOnSkins");

if(not addon:CheckAddOn("GnomishVendorShrinker")) then return; end

function addon:GnomishVendorShrinker()
	local S = E:GetModule("Skins");

	GVSEditBox:StripTextures();
	S:HandleEditBox(GVSEditBox)
	GVSEditBox:SetWidth(135);
	GVSEditBox:SetHeight(19);
	GVSEditBox:SetScale(1.07);
	GVSMerchantFrame:CreateBackdrop("Transparent");
	S:HandleButton(GVSScrollButton1)
	S:HandleButton(GVSScrollButton2)
	GVSScrollFrame:StripTextures();
	S:HandleSliderFrame(GVSScrollBar)

end

addon:RegisterSkin("GnomishVendorShrinker", addon.GnomishVendorShrinker);

Pictures:
![wowscrnshot_041716_093730](https://cloud.githubusercontent.com/assets/16202997/14585499/68717c28-0481-11e6-85b1-60c2539185d8.png)
![wowscrnshot_041716_093804](https://cloud.githubusercontent.com/assets/16202997/14585500/6b5ddc10-0481-11e6-8054-acb60c9b59e3.png)
![wowscrnshot_041716_093856](https://cloud.githubusercontent.com/assets/16202997/14585501/6e5b3110-0481-11e6-862d-18e16937edb7.png)

This Skin will work only with this version of the Addon:
http://www.mediafire.com/download/oa9zscfpg8ydbb7/GnomishVendorShrinker+3.3.5+[ElvUI].rar

**Comment by Bunny67** [comment]
Check
