### ISSUE TITLE
Blacklist - Skin

### ISSUE THREAD

**Issue by Lexblack** [ElvUI/ElvUI_AddOnSkins#25]
Code:
local E, L, V, P, G, _ = unpack(ElvUI);
local addon = E:GetModule("AddOnSkins");

if(not addon:CheckAddOn("BlackList")) then return; end

function addon:BlackList()
	local S = E:GetModule("Skins");

	S:HandleButton(FriendsFrameOptionsButton);
	S:HandleButton(FriendsFrameShareListButton);
	S:HandleButton(FriendsFrameRemovePlayerButton);
	S:HandleButton(FriendsFrameBlacklistPlayerButton);
	FriendsTabHeaderTab4:StripTextures();
	FriendsTabHeaderTab4:SetWidth(63)
	FriendsTabHeaderTab4:SetHeight(26)
	FriendsTabHeaderTab4:Point("TOPLEFT",FriendsTabHeaderTab3, "TOPLEFT", 3, -7)
	S:HandleButton(FriendsTabHeaderTab4);

	S:HandleCloseButton(BlackListDetailsCloseButton)
	BlackListDetailsFrame:StripTextures();
	BlackListDetailsFrame:SetTemplate("Transparent");
	BlackListDetailsFrameReasonTextBackground:StripTextures();
	BlackListDetailsFrameReasonTextBackground:CreateBackdrop("Default");
	S:HandleButton(BlackListDetailsEditButton);
	S:HandleCheckBox(BlackListDetailsFrameCheckButton1);
	S:HandleCheckBox(BlackListDetailsFrameCheckButton2);
	S:HandleScrollBar(BlackListDetailsFrameScrollFrameScrollBar)

	BlackListEditDetailsFrame:StripTextures();
	BlackListEditDetailsFrame:SetTemplate("Transparent");
	BlackListEditDetailsFrameLevelBackground:StripTextures();
	BlackListEditDetailsFrameLevelBackground:CreateBackdrop("Default");
	BlackListEditDetailsFrameLevelBackground.backdrop:Point('TOPLEFT', 5, -3);
	BlackListEditDetailsFrameLevelBackground.backdrop:Point('BOTTOMRIGHT', -5, 5);
	S:HandleButton(BlackListEditDetailsFrameSaveButton)
	S:HandleButton(BlackListEditDetailsFrameCancelButton)
	S:HandleDropDownBox(BlackListEditDetailsFrameClassDropDown)
	S:HandleDropDownBox(BlackListEditDetailsFrameRaceDropDown)

	BlackListOptionsFrame:StripTextures();
	BlackListOptionsFrame:SetTemplate("Transparent");
	S:HandleCheckBox(SoundCheckButton)
	S:HandleCheckBox(CenterCheckButton)
	S:HandleCheckBox(ChatCheckButton)
	S:HandleCheckBox(IgnoreCheckButton)
	S:HandleCheckBox(BanCheckButton)
	S:HandleCheckBox(KickCheckButton)
	S:HandleEditBox(BL_RankBox)
	BL_RankBox:SetWidth(20)
	BL_RankBox:SetHeight(20)

end

addon:RegisterSkin("BlackList", addon.BlackList);

Picture:
![wowscrnshot_041916_120626](https://cloud.githubusercontent.com/assets/16202997/14633665/55d492d8-0627-11e6-9074-508571dfda84.jpg)

**Comment by Bunny67** [comment]
Check
