### ISSUE TITLE
AllStats - Skin

### ISSUE THREAD

**Issue by Lexblack** [ElvUI/ElvUI_AddOnSkins#26]
Code:
local E, L, V, P, G, _ = unpack(ElvUI);
local addon = E:GetModule("AddOnSkins");

if(not addon:CheckAddOn("AllStats")) then return; end

function addon:AllStats()
	local S = E:GetModule("Skins");

	AllStatsFrame:StripTextures();
	AllStatsFrame:CreateBackdrop("Transparent");
	AllStatsFrame:SetHeight(422)
	AllStatsFrame:Point("TOPLEFT",PaperDollFrame, "TOPLEFT", 352, -13)
	S:HandleButton(AllStatsButtonShowFrame)

end

addon:RegisterSkin("AllStats", addon.AllStats);

Picture:
![wowscrnshot_041916_162532](https://cloud.githubusercontent.com/assets/16202997/14640702/6fe8361a-064b-11e6-9cf1-cfb4dc930736.jpg)

**Comment by Bunny67** [comment]
Check
