### ISSUE TITLE
MoveAnything - Skin

### ISSUE THREAD

**Issue by Lexblack** [ElvUI/ElvUI_AddOnSkins#27]
local E, L, V, P, G, _ = unpack(ElvUI);
local addon = E:GetModule("AddOnSkins");

if(not addon:CheckAddOn("MoveAnything")) then return; end

function addon:MoveAnything()
	local S = E:GetModule("Skins");

	S:HandleButton(GameMenuButtonMoveAnything)

	MAOptions:StripTextures();
	MAOptions:SetTemplate("Transparent");

	MAScrollBorder:StripTextures();
	S:HandleScrollBar(MAScrollFrameScrollBar)

	S:HandleButton(MAOptionsSync)
	S:HandleButton(MAOptionsClose)
	S:HandleButton(MAOptionsResetAll)

	S:HandleCheckBox(MAOptionsToggleModifiedFramesOnly)
	S:HandleCheckBox(MAOptionsToggleCategories)
	S:HandleCheckBox(MAOptionsToggleTooltips)
	S:HandleCheckBox(MAOptionsCharacterSpecific)

	for i = 1, 100 do
		if _G['MAMove'..i..'Reset'] then S:HandleButton(_G['MAMove'..i..'Reset'])
		end
		if _G['MAMove'..i..'Reset'] then S:HandleButton(_G['MAMove'..i..'Reset'])
		end
		if _G['MAMove'..i..'Move'] then S:HandleCheckBox(_G['MAMove'..i..'Move'])
		end
		if _G['MAMove'..i..'Hide'] then S:HandleCheckBox(_G['MAMove'..i..'Hide'])
		end
		if _G['MAMove'..i..'Backdrop'] then (_G['MAMove'..i..'Backdrop']):StripTextures();
		end
		if _G['MAMove'..i..'Backdrop'] then (_G['MAMove'..i..'Backdrop']):CreateBackdrop("Transparent");
		end
	end

	MANudger:StripTextures();
	MANudger:SetTemplate("Transparent");

	S:HandleButton(MANudger_CenterMe)
	S:HandleButton(MANudger_CenterH)
	S:HandleButton(MANudger_CenterV)
	S:HandleButton(MANudger_NudgeUp)
	S:HandleButton(MANudger_NudgeDown)
	S:HandleButton(MANudger_NudgeLeft)
	S:HandleButton(MANudger_NudgeRight)
	S:HandleButton(MANudger_Detach)
	S:HandleButton(MANudger_Hide)
	S:HandleButton(MANudger_MoverMinus)
	S:HandleButton(MANudger_MoverPlus)

end

addon:RegisterSkin("MoveAnything", addon.MoveAnything);

![wowscrnshot_042416_095326](https://cloud.githubusercontent.com/assets/16202997/14765972/a37ee6ee-0a02-11e6-914f-e74cd443a2ae.jpg)

**Comment by Bunny67** [comment]
check
