### ISSUE TITLE
BNetToast - Skin

### ISSUE THREAD

**Issue by crumdidlyumshis** [ElvUI/ElvUI_AddOnSkins#29]
https://github.com/Bunny67/BNetToast
https://github.com/crumdidlyumshis/BNetToast
https://github.com/Kkthnx/BNetToast

local E, L, V, P, G, _ = unpack(ElvUI);
local addon = E:GetModule("AddOnSkins");

if(not addon:CheckAddOn("BNetToast")) then return; end

function addon:BNetToast()
	local S = E:GetModule("Skins");
	BNToastFrameCloseButton:SetWidth(32);
	BNToastFrameCloseButton:SetHeight(32);
	BNToastFrameCloseButton:SetPoint("TOPRIGHT","BNToastFrame", 4, 3);
	S:HandleCloseButton(BNToastFrameCloseButton);
end

addon:RegisterSkin("BNetToast", addon.BNetToast);

**Comment by Bunny67** [comment]
I think better to add ElvUI https://github.com/ElvUI/ElvUI/commit/d8f68ffa82023aade975c67cfdcde64f8b5a785b
