### ISSUE TITLE
New Tab Toggle Option

### ISSUE THREAD

**Issue by crumdidlyumshis** [ElvUI/ElvUI_AddOnSkins#30]
https://github.com/ElvUI/ElvUI_AddOnSkins/commit/1b97be368bfeea8a966e84025c0690494de59ad5

https://www.youtube.com/watch?v=IueRfpGH-Wg

**Comment by crumdidlyumshis** [comment]
https://github.com/ElvUI/ElvUI_AddOnSkins/commit/339119cecf10a48b311f4c6f3ac67013377137eb

https://youtu.be/HdWsxR-z58E

**Comment by crumdidlyumshis** [comment]
Ohhhhh If the option "Hide Chat Frame" is set to "Loot/Trade" it bugs.

If it is set to anything else, it works fine.

**Comment by crumdidlyumshis** [comment]
This is what bugs it.

![world of warcraft 8_27_2016 7_42_31 pm](https://cloud.githubusercontent.com/assets/7307335/18030888/7caf8228-6c8e-11e6-8d8c-b6b8a46fee1a.png)

**Comment by crumdidlyumshis** [comment]
Could you make it do this?

https://youtu.be/_qe4HCdf3cQ

**Comment by Bunny67** [comment]
check

**Comment by Bunny67** [comment]
tomorrow, think about the last video

**Comment by crumdidlyumshis** [comment]
https://github.com/ElvUI/ElvUI_AddOnSkins/commit/777dc15f168270dc45ac6ce2b9f8ebdf89d27930

https://youtu.be/4zsVyJNo-cE

**Comment by Bunny67** [comment]
update alpha
no another way :(

**Comment by Bunny67** [comment]
last video tomorrow check :(

**Comment by Bunny67** [comment]
Strangely, I was not able to reproduce the error

**Comment by crumdidlyumshis** [comment]
It works better now! Thank you!

But if it was possible, could you make it toggle like so?

https://github.com/ElvUI/ElvUI_AddOnSkins/issues/30#issuecomment-242949223

**Comment by Bunny67** [comment]
I have not found an easy way to do it, change the transparency of trade tab. There is an option, but it will break the tab, and you have to restart the interface. No other ideas :(

**Comment by crumdidlyumshis** [comment]
That is alright. This is more than I could ask for! Great job!

If you ever find a way to make the Loot/Tab and Skada toggle-able, that would be awesome!

This will work just fine :) :+1:
