### ISSUE TITLE
Clique - Skin

### ISSUE THREAD

**Issue by crumdidlyumshis** [ElvUI/ElvUI_AddOnSkins#8]
Would it be possible to have Clique skinned? I have been trying but my knowledge is lacking.

**Comment by crumdidlyumshis** [comment]
I may have all this wrong, but I got it to appear correct.

Could you add this?



		S:HandleDropDownBox(CliqueDropDown);
		CliqueDropDown:SetPoint("TOPRIGHT", -1, -25);

		S:HandleCloseButton(CliqueButtonClose);
		S:HandleCloseButton(CliqueOptionsButtonClose);
		CliqueButtonClose:SetWidth(32);
		CliqueButtonClose:SetHeight(32);
		CliqueButtonClose:SetPoint("TOPRIGHT", 5, 5);
		CliqueOptionsButtonClose:SetWidth(32);
		CliqueOptionsButtonClose:SetHeight(32);
		CliqueOptionsButtonClose:SetPoint("TOPRIGHT", 5, 5);
		CliqueTextButtonClose:SetWidth(32);
		CliqueTextButtonClose:SetHeight(32);
		CliqueTextButtonClose:SetPoint("TOPRIGHT", 5, 5);

		S:HandleDropDownBox(CliquePriSpecDropDown);
		S:HandleDropDownBox(CliqueSecSpecDropDown);
		CliquePriSpecDropDown:SetWidth(225);
		CliqueSecSpecDropDown:SetWidth(225);
		CliquePriSpecDropDownButton:SetWidth(20);
		CliqueSecSpecDropDownButton:SetWidth(20);
		CliquePriSpecDropDownButton:SetHeight(20);
		CliqueSecSpecDropDownButton:SetHeight(20);

		CliqueTextListScrollScrollBar:SetPoint("TOPLEFT", CliqueTextListFrame, "TOPRIGHT", -26, -42)

		local cliqueConfigCheck = {
			"CliqueOptionsAnyDown",
			"CliqueOptionsSpecSwitch",
			"CliqueTextList1",
			"CliqueTextList2",
			"CliqueTextList3",
			"CliqueTextList4",
			"CliqueTextList5",
			"CliqueTextList6",
			"CliqueTextList7",
			"CliqueTextList8",
			"CliqueTextList9",
			"CliqueTextList10",
			"CliqueTextList11",
			"CliqueTextList12",
		};

		for i = 1, getn(cliqueConfigCheck) do
			S:HandleCheckBox(_G[cliqueConfigCheck[i]]);
			_G[cliqueConfigCheck[i]]:SetWidth(24);
			_G[cliqueConfigCheck[i]]:SetHeight(24);
		end

		CliqueFrame:SetHeight(426);
		CliqueFrame:SetPoint("TOPLEFT", SpellBookFrame, "TOPRIGHT", 10, -11);

**Comment by crumdidlyumshis** [comment]
![wowscrnshot_030616_222645](https://cloud.githubusercontent.com/assets/7307335/13560875/a36b847a-e3ea-11e5-987f-f55cc46369fe.jpg)

**Comment by Bunny67** [comment]
You can link to download, I do not have this version

**Comment by crumdidlyumshis** [comment]
I think I use this: http://wow.curseforge.com/addons/clique/files/65-r139-release/

**Comment by Bunny67** [comment]
The 139 version does not have this button

**Comment by crumdidlyumshis** [comment]
Hmm, I will check when I get home. You are probably correct.

**Comment by crumdidlyumshis** [comment]
I had an old version. Reinstalled newer version and it works. Sorry for the confusion.
