### ISSUE TITLE
Spy - Skin

### ISSUE THREAD

**Issue by crumdidlyumshis** [ElvUI/ElvUI_AddOnSkins#9]
Download: http://www.curse.com/addons/wow/spy

local E, L, V, P, G, _ = unpack(ElvUI);
local addon = E:GetModule("AddOnSkins");

if(not addon:CheckAddOn("Spy")) then return; end

function addon:Spy()
	local S = E:GetModule("Skins");
	Spy_MainWindow:StripTextures();
	Spy_MainWindow:SetTemplate("Transparent");
end

addon:RegisterSkin("Spy", addon.Spy);

**Comment by Bunny67** [comment]
added
